spring.application.name=EPAMtask1

storage.trainees.file.path=data/trainees.json
storage.trainers.file.path=data/trainers.json
storage.trainings.file.path=data/trainings.json

spring.datasource.url=jdbc:postgresql://localhost:5432/EpamTrainingTask
spring.datasource.username=postgres
spring.datasource.password=Hahiti14

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
