spring.application.name=EPAMtask1

spring.profiles.active=local

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

management.endpoints.web.exposure.include=health,metrics,info,prometheus
management.endpoint.health.show-details=always